[common]
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts = pre:get_git_hash.py
lib_deps =
    jgromes/RadioLib
    mathieucarbou/ESP Async WebServer
    mathieucarbou/AsyncTCP
    bblanchon/ArduinoJson

[env:esp32_sx1276]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = ${common.extra_scripts}
build_flags = -DHARDWARE_ESP32_SX1276 -DDEVELOPMENT
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
    ${common.lib_deps}

[env:esp32_sx1276_dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = ${common.extra_scripts}
build_flags = -DHARDWARE_ESP32_SX1276 -DDEVELOPMENT
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
    ${common.lib_deps}

[env:heltec_v3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
extra_scripts = ${common.extra_scripts}
build_flags = -DHARDWARE_HELTEC_V3 -DDEVELOPMENT
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
    ${common.lib_deps}
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

[env:heltec_v3_dev]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
extra_scripts = ${common.extra_scripts}
build_flags = -DHARDWARE_HELTEC_V3 -DDEVELOPMENT
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
    ${common.lib_deps}
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

[env:heltec_v3_prod]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
extra_scripts = ${common.extra_scripts}
build_flags = -DHARDWARE_HELTEC_V3
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
    ${common.lib_deps}
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library